const { ethers, network } = require("hardhat");
const fs = require("fs");
const path = require("path");

/**
 * DEV-ONLY: deploy StockVesting + two MockB20 tokens (AAPLc/NVDAc, decimals 8 to
 * mirror the real Base tokens) to a local Hardhat node, mint stock to the first
 * account, and write web/.env.local so the app runs in local end-to-end mode.
 *
 * Usage:
 *   npx hardhat node                     # terminal 1
 *   npx hardhat run scripts/deploy-local.js --network localhost   # terminal 2
 *
 * This never touches mainnet or real funds.
 */
async function main() {
  const net = await ethers.provider.getNetwork();
  if (net.chainId !== 31337n) {
    throw new Error(`deploy-local is for the local node (31337); got ${net.chainId}`);
  }
  const [deployer, recipient] = await ethers.getSigners();
  console.log(`network: ${network.name} (chainId ${net.chainId})`);
  console.log(`deployer:  ${deployer.address}`);
  console.log(`recipient: ${recipient.address}`);

  const Mock = await ethers.getContractFactory("MockB20");
  const aapl = await Mock.deploy("Apple Inc.", "AAPLc", 8);
  await aapl.waitForDeployment();
  const nvda = await Mock.deploy("NVIDIA Corporation", "NVDAc", 8);
  await nvda.waitForDeployment();

  const mintAmt = 1000n * 10n ** 8n; // 1000 shares in raw units (8 decimals)
  await (await aapl.mint(deployer.address, mintAmt)).wait();
  await (await nvda.mint(deployer.address, mintAmt)).wait();

  const Vesting = await ethers.getContractFactory("StockVesting");
  const vesting = await Vesting.deploy();
  await vesting.waitForDeployment();

  const aaplAddr = await aapl.getAddress();
  const nvdaAddr = await nvda.getAddress();
  const vestingAddr = await vesting.getAddress();

  console.log("\nDeployed (local):");
  console.log(`  StockVesting: ${vestingAddr}`);
  console.log(`  AAPLc (mock): ${aaplAddr}`);
  console.log(`  NVDAc (mock): ${nvdaAddr}`);

  const env = [
    "# DEV-ONLY local end-to-end config generated by deploy-local.js.",
    "# Do NOT use in production. Delete this file to return to Base mainnet mode.",
    "NEXT_PUBLIC_ENABLE_LOCAL=true",
    "NEXT_PUBLIC_LOCAL_RPC_URL=http://127.0.0.1:8545",
    `NEXT_PUBLIC_STOCK_VESTING_ADDRESS=${vestingAddr}`,
    `NEXT_PUBLIC_AAPLC_ADDRESS=${aaplAddr}`,
    `NEXT_PUBLIC_NVDAC_ADDRESS=${nvdaAddr}`,
    "",
  ].join("\n");
  const envPath = path.resolve(__dirname, "..", "..", "web", ".env.local");
  fs.writeFileSync(envPath, env);
  console.log(`\nWrote ${envPath}`);
  console.log(`Demo recipient to paste in the Pay form: ${recipient.address}`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
