// PM2 process definition for the shared Qevor VPS.
// OwnPay gets its own process name and listens only on loopback port 3102.
module.exports = {
  apps: [
    {
      name: "ownpay-web",
      cwd: process.env.OWNPAY_WEB_ROOT || "/opt/ownpay/web",
      script: `${process.env.OWNPAY_BUILD_DIR || ".next"}/standalone/server.js`,
      env: {
        NODE_ENV: "production",
        HOSTNAME: "127.0.0.1",
        PORT: process.env.OWNPAY_PORT || "3102",
        NEXT_TELEMETRY_DISABLED: "1",
        OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL,
        OLLAMA_MODEL: process.env.OLLAMA_MODEL,
        OLLAMA_API_KEY: process.env.OLLAMA_API_KEY,
        DATABASE_URL: process.env.DATABASE_URL,
        PRIVY_VERIFICATION_KEY: process.env.PRIVY_VERIFICATION_KEY,
        NEXT_PUBLIC_PRIVY_APP_ID: process.env.NEXT_PUBLIC_PRIVY_APP_ID,
        NEXT_PUBLIC_PRIVY_KEY_QUORUM_ID: process.env.NEXT_PUBLIC_PRIVY_KEY_QUORUM_ID || process.env.PRIVY_KEY_QUORUM_ID,
        PRIVY_APP_ID: process.env.PRIVY_APP_ID || process.env.NEXT_PUBLIC_PRIVY_APP_ID,
        PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
        PRIVY_KEY_QUORUM_ID: process.env.PRIVY_KEY_QUORUM_ID,
        OWNPAY_DPRI_ROUTE_ENABLED: process.env.OWNPAY_DPRI_ROUTE_ENABLED,
        OWNPAY_B20_ROUTE_ENABLED: process.env.OWNPAY_B20_ROUTE_ENABLED,
        OWNPAY_B20_VENUE: process.env.OWNPAY_B20_VENUE,
        ROBINHOOD_TESTNET_RPC_URL: process.env.ROBINHOOD_TESTNET_RPC_URL,
        ROBINHOOD_OWNRULES_ADDRESS: process.env.ROBINHOOD_OWNRULES_ADDRESS,
        ROBINHOOD_DEMO_ADAPTER_ADDRESS: process.env.ROBINHOOD_DEMO_ADAPTER_ADDRESS,
        ROBINHOOD_DEMO_ASSET_ADDRESS: process.env.ROBINHOOD_DEMO_ASSET_ADDRESS,
        ROBINHOOD_DEPLOYMENT_BLOCK: process.env.ROBINHOOD_DEPLOYMENT_BLOCK,
        ROBINHOOD_RELAY_PRIVATE_KEY: process.env.ROBINHOOD_RELAY_PRIVATE_KEY,
        ROBINHOOD_SPONSORED_OWNERS: process.env.ROBINHOOD_SPONSORED_OWNERS,
        ROBINHOOD_AGENT_ADDRESS: process.env.ROBINHOOD_AGENT_ADDRESS,
        ROBINHOOD_AGENT_HEALTH_FILE: process.env.ROBINHOOD_AGENT_HEALTH_FILE,
        PRIVY_AUTHORIZATION_PRIVATE_KEY: process.env.PRIVY_AUTHORIZATION_PRIVATE_KEY,
      },
    },
    {
      name: "ownpay-agent",
      cwd: "/opt/ownpay/web",
      script: "agent/ownership-agent.mjs",
      autorestart: true,
      restart_delay: 5000,
      env: {
        NODE_ENV: "production",
        AGENT_RPC_URL: process.env.AGENT_RPC_URL,
        AGENT_CHAIN_ID: process.env.AGENT_CHAIN_ID,
        AGENT_USDC_ADDRESS: process.env.AGENT_USDC_ADDRESS,
        AGENT_START_BLOCK: process.env.AGENT_START_BLOCK,
        AGENT_BLOCK_CHUNK: process.env.AGENT_BLOCK_CHUNK || "500",
        AGENT_POLL_INTERVAL_MS: process.env.AGENT_POLL_INTERVAL_MS,
        OWNPAY_AGENT_MODE: process.env.OWNPAY_AGENT_MODE || "observe",
        OWNPAY_B20_ROUTE_ENABLED: process.env.OWNPAY_B20_ROUTE_ENABLED,
        OWNPAY_B20_VENUE: process.env.OWNPAY_B20_VENUE,
        OWNPAY_DPRI_ROUTE_ENABLED: process.env.OWNPAY_DPRI_ROUTE_ENABLED,
        OWNPAY_B20_ROUTER_ADDRESS: process.env.OWNPAY_B20_ROUTER_ADDRESS,
        PRIVY_APP_ID: process.env.PRIVY_APP_ID || process.env.NEXT_PUBLIC_PRIVY_APP_ID,
        PRIVY_APP_SECRET: process.env.PRIVY_APP_SECRET,
        PRIVY_AUTHORIZATION_PRIVATE_KEY: process.env.PRIVY_AUTHORIZATION_PRIVATE_KEY,
        PRIVY_KEY_QUORUM_ID: process.env.PRIVY_KEY_QUORUM_ID,
        DATABASE_URL: process.env.DATABASE_URL,
      },
    },
  ],
};
